TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := true

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a57

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a57
TARGET_BOARD_PLATFORM := switch

TARGET_USES_64_BIT_BINDER := true 

TARGET_USERIMAGES_USE_EXT4 := true

BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2036870912 # 512M
BOARD_USERDATAIMAGE_PARTITION_SIZE := 134217728 # 128M

# Graphics
TARGET_USES_HWC2 := true
USE_OPENGL_RENDERER := true
SF_PRIMARY_DISPLAY_ORIENTATION := 270
ifneq ($(TARGET_GRAPHICS_DRIVER),swiftshader)
BOARD_USES_DRM_HWCOMPOSER := true
BOARD_USES_DRM_GRALLOC := true
BOARD_DISABLE_TRIPLE_BUFFERED_DISPLAY_SURFACES := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
endif

ifeq ($(TARGET_GRAPHICS_DRIVER),mesa)
BOARD_GPU_DRIVERS := nouveau tegra
endif

ifeq ($(TARGET_GRAPHICS_DRIVER),nvgpu)
BOARD_GPU_DRIVERS := tegra
endif

# Wifi
BOARD_WLAN_DEVICE := bcmdhd
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_bcmdhd
BOARD_HOSTAPD_PRIVATE_LIB   := lib_driver_cmd_bcmdhd
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211

USE_CAMERA_STUB := true
